<a href="https://colab.research.google.com/github/Adhira-Deogade/INFO-7374---Assignment-3/blob/master/Vectorizing_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
'All my cats in a row',
'When my cat sits down, she looks like a Furby toy!',
'The cat from outer space',
'Sunshine loves to sit like this for some reason.'
]

vectorizer = CountVectorizer()
print( vectorizer.fit_transform(corpus).todense() )
print( vectorizer.vocabulary_ )

[[1 0 1 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 1 0 1 1 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 1]
 [0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0]]
{'all': 0, 'my': 11, 'cats': 2, 'in': 7, 'row': 14, 'when': 25, 'cat': 1, 'sits': 17, 'down': 3, 'she': 15, 'looks': 9, 'like': 8, 'furby': 6, 'toy': 24, 'the': 21, 'from': 5, 'outer': 12, 'space': 19, 'sunshine': 20, 'loves': 10, 'to': 23, 'sit': 16, 'this': 22, 'for': 4, 'some': 18, 'reason': 13}


**Bag of words example**

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
vectorizer = CountVectorizer()

In [0]:
from google.colab import files

In [6]:
upload = files.upload()

Saving cleanedfinancial_data.csv to cleanedfinancial_data (1).csv


In [7]:
ls

'cleanedfinancial_data (1).csv'   FinanceSentiments.csv
 cleanedfinancial_data.csv        sample_data/


In [0]:
import pandas as pd
import numpy as np

In [0]:
df = pd.read_csv("cleanedfinancial_data.csv")

In [10]:
df.head()

Unnamed: 0 sentiment                                               text
0           0   neutral  Good day, ladies and gentlemen, and welcome to...
1           1  negative  I'm not sure. I think Model T was a little bit...
2           2  negative  Well, we need to bring the Shanghai factory on...
3           3   neutral  So it's - it is eligible for that. But it soun...
4           4  positive  The demand for - the demand for Model 3 is ins...

In [0]:
df.drop(columns='Unnamed: 0', inplace=True)

In [12]:
df.head()

sentiment                                               text
0   neutral  Good day, ladies and gentlemen, and welcome to...
1  negative  I'm not sure. I think Model T was a little bit...
2  negative  Well, we need to bring the Shanghai factory on...
3   neutral  So it's - it is eligible for that. But it soun...
4  positive  The demand for - the demand for Model 3 is ins...

In [13]:
df.shape

(1649, 2)